RAW_INPUT_DIR       = 'data/raw_input/'
RAW_INPUT_FILE      = 'Concrete_Data.csv'
EXP_OUTPUT_DIR      = 'experiments/outputs/'
EXP_CONFIG_DIR      = 'experiments/configs/'
EXP_SCRIPT_DIR      = 'experiments/scripts/'
LOGS_DIR            = 'logs/runtime/'
TEST_OUTPUT_DIR     = 'logs/test_output/'