PATH_RAW_INPUT_DIR      = 'data/raw_input/'
PATH_RAW_INPUT_FILE     = 'Concrete_Data.csv'
PATH_EXP_OUTPUT_DIR     = 'experiments/outputs/'
PATH_EXP_CONFIG_DIR     = 'experiments/configs/'
PATH_EXP_SCRIPT_DIR     = 'experiments/scripts/'
PATH_RUNTIME_LOG_DIR    = 'logs/runtime/'
PATH_TEST_OUTPUT_DIR    = 'logs/test_output/'