output:
  normalized_input_dir: data/normalized_input
  test_output_dir: data/test_output
  log_level: INFO
  save_config_copy: true    # save merged config with results
  save_metrics: true        # save metrics.json in run folder
  timestamp_format: "%Y%m%d-%H%M%S"