# ========== PSO CONFIG (Algorithm 39 - 3 acceleration coefficients) ==========
pso:
  # --- Search budget ---
  swarm_size: 25            # number of particles
  iterations: 20            # number of PSO update iterations

  # --- Velocity update coefficients ---
  inertia: 0.7              # w (momentum term)
  cognitive: 1.5            # c1 (personal best attraction)
  social_local: 1.5         # c2 (informants/neighborhood best)
  social_global: 1.5        # c3 (global best)

  # --- Neighborhood / topology ---
  topology: informants      # options: informants | ring | global
  informants_k: 3           # used when topology = informants

  # --- Velocity limits ---
  min_velocity: -0.2
  max_velocity: 0.2

  # --- Boundary handling ---
  boundary:
    handling: clamp          # options: clamp | reflect
    source: ann_init_range   # use ANN weight init range for parameter bounds

    clamp:
      epsilon: 0.0            # small margin inside bounds (optional)

    reflect:
      coefficient: 1.0        # 1.0 = perfect reflection; <1.0 = damped
